eno.host=https://api.deepseek.com
eno.chatMethod=/v1/chat/completions
eno.token=sk-3bd7de4412a74b0d9c9fdee6c0f7bac2
eno.model=deepseek-chat
eno.contentType=application/json

qwen.host=http://localhost:11434
qwen.chatMethod=/api/generate
qwen.token=
qwen.model=qwen:7b
qwen.contentType=application/json